;;; snap.el --- Snapshot Testing for Emacs Lisp -*- lexical-binding: t -*-

;; Copyright (c) 2025 Musa Al-hassy

;; Author: Musa Al-hassy <alhassy@gmail.com>
;; Version: 0.1.0
;; Package-Requires: ((s "1.13.1") (emacs "27.1") (magit "3.0"))
;; Keywords: testing, snapshot, ert
;; URL: https://github.com/alhassy/snap

;; This program is free software; you can redistribute it and/or modify
;; it under the terms of the GNU General Public License as published by
;; the Free Software Foundation, either version 3 of the License, or
;; (at your option) any later version.

;;; Commentary:
;;
;; Snapshot testing infrastructure for ERT.  Three layers:
;;
;; 1. `deftestfixture' — macro-generating macro.  Wraps test bodies in
;;    a fixture (setup/teardown), generates a test macro with
;;    string-based naming and auto-derived tags, and registers it so
;;    `C-x C-e' both defines and runs the test in one keystroke.
;;
;; 2. `define-relation' — relational test fixtures with snapshot
;;    updating.  Declares a relation among parameters (some inputs,
;;    some outputs), generates a test macro, a compute function (with
;;    `ert-fail' suppressed for snapshot update), `C-u C-x C-e'
;;    plumbing, and [Show Diff] / [Update Snapshot] buttons on failure.
;;
;; 3. `deftest' — the simplest case: `(deftestfixture deftest)' with
;;    no fixture wrapping.  A strict improvement over raw `ert-deftest'.

;;; Code:

(require 'cl-lib)
(require 'ert)
(require 's)
(require 'seq)

;; ═══════════════════════════════════════════════════════════════════
;; Registry and eval-last-sexp advice
;; ═══════════════════════════════════════════════════════════════════

(defvar deftestfixture--registry (make-hash-table :test 'eq)
  "Set of macro names generated by `deftestfixture'.
Used by `my/eval-last-sexp--run-test' to detect when `C-x C-e'
is invoked on a test form, so it can eval-and-run in one step.")

(defun my/eval-last-sexp--run-test (orig-fn prefix-arg &rest args)
  "Around `eval-last-sexp': detect `deftestfixture'-registered forms.

Plain `C-x C-e' -> eval the form, then immediately run the test.
`C-u C-x C-e' on a `define-relation'-generated test -> update the
snapshot output keys instead of evaluating.  Magit then shows the
diff of old vs new snapshot.

The registry (`deftestfixture--registry') stores either `t' (for
plain `deftestfixture' macros) or a plist with `:updater' (for
`define-relation' macros).  The `:updater' function rewrites the
output keys in the source buffer."
  (let ((updater nil))
    ;; Peek at the form before eval-last-sexp moves point.
    (save-excursion
      (backward-sexp)
      (when-let* ((form (sexp-at-point))
                  (_    (consp form))
                  (head (car form))
                  (entry (gethash head deftestfixture--registry)))
        (when (and prefix-arg
                   (consp entry)
                   (plist-get entry :updater))
          (setq updater (plist-get entry :updater)))))
    (if updater
        ;; Intercept: update snapshot without letting eval-last-sexp
        ;; insert its result into the buffer (C-u behaviour).
        (funcall updater)
      ;; Normal eval.
      (apply orig-fn prefix-arg args)
      ;; After eval, auto-run the test if it's a registered form.
      (save-excursion
        (backward-sexp)
        (when-let* ((form (sexp-at-point))
                    (_    (consp form))
                    (head (car form))
                    (_    (gethash head deftestfixture--registry)))
          (let ((expanded (macroexpand-1 form)))
            (when (and (consp expanded)
                       (eq (car expanded) 'ert-deftest))
              (let ((test-name (cadr expanded)))
                (message "Running test: %s" test-name)
                (ert test-name)))))))))

(advice-add 'eval-last-sexp :around #'my/eval-last-sexp--run-test)

;; ═══════════════════════════════════════════════════════════════════
;; deftestfixture — macro-generating macro for test fixtures
;; ═══════════════════════════════════════════════════════════════════

(defvar deftest-space "·"
  "The symbol used in place of whitespace in test names.
The default is interpunct style (middle dot).  Alternatives:
  - Hyphens:     OSBE-org-source-exports
  - Snakecase:   OSBE_org_source_exports
  - Underbracket: OSBE␣org␣source␣exports")

(cl-defmacro deftestfixture (name &optional docstring-or-form fixture-form)
  "Define a new test macro NAME that wraps each test body in FIXTURE-FORM.
A test fixture is the fixed baseline state that tests run against --
the setup that must be in place before the test logic executes.  By
way of example: a temp directory, a database connection, or config
variable bindings.  The name reads as \"define a test-with-fixture
macro\", which is precisely what it does.

ERT (6.2) deliberately omits fixture syntax, noting that
`with-my-fixture' macros are the idiomatic Lisp approach and that
\"special syntax for them could be added but would provide only a
minor simplification.\"  This macro is that minor simplification:
it defines the `with-my-fixture' wrapper and wires it into
`ert-deftest' -- with string-based naming and auto-derived tags --
in one step.

Each generated macro is also registered so that `C-x C-e'
\(`eval-last-sexp') both defines and runs the test in one
keystroke -- no separate `M-x ert' invocation needed.

NAME is the symbol for the generated macro.  DOCSTRING-OR-FORM is
either a documentation string (when FIXTURE-FORM is also provided)
or the fixture form itself (when no docstring is needed).  When
both are omitted, the generated macro has no fixture -- its body is
spliced directly into `ert-deftest'.

FIXTURE-FORM is an expression with a hole for the body -- represented
by the symbol `&body'.  When nil, the body is spliced directly
\(no wrapping).

The generated macro has the signature:
  (NAME DESCRIPTION &optional TAGS &rest BODY)
where DESCRIPTION is a string and TAGS is an optional vector.

Example -- define `deftest' (the identity, no fixture):
  (deftestfixture deftest)

Even this trivial case is already an improvement over raw
`ert-deftest': test names are natural-language strings (not
hand-mangled symbols), tags are auto-derived from the first
word, and the boilerplate docstring + :tags declaration
disappears entirely.

Example -- define `defworkitemtest' with a docstring and fixture:
  (deftestfixture defworkitemtest
    \"Bind Gerrit/Jira config vars to safe test defaults.\"
    (let ((my\\\\jira-ticket-regex ...)
          (my\\\\gerrit-base-url ...))
      &body))

Then:
  (defworkitemtest \"work-item shows Jira ticket\" [work-item]
    (should ...))

expands to an `ert-deftest' wrapped in the fixture bindings.

Snapshot testing pattern:
For relational tests -- where inputs produce expected outputs and
you want `C-u C-x C-e' to auto-fill the expectations -- use
`define-relation' instead.  It generates a test macro with
snapshot update, magit-styled [Show Diff], and [Update Snapshot]
buttons in ERT failure output."
  (declare (indent 1))
  ;; Disambiguate: if DOCSTRING-OR-FORM is a string, it's a docstring
  ;; and FIXTURE-FORM is the fixture.  Otherwise DOCSTRING-OR-FORM is
  ;; the fixture and there is no docstring.
  (let* ((user-docstring (when (stringp docstring-or-form)
                           docstring-or-form))
         (fixture-form   (if (stringp docstring-or-form)
                             fixture-form
                           docstring-or-form))
         (ert-usage "\n\n\
BODY is evaluated as a `progn' when the test is run.  It should
signal a condition on failure or just return if the test passes.

`should', `should-not', `should-error', `skip-when', and
`skip-unless' are useful for assertions in BODY.

Use `ert' to run tests interactively.  Even easier: `C-x C-e'
at the end of a test form both defines and runs it in one
keystroke, courtesy of `deftestfixture--registry'.

Tests that are expected to fail can be marked as such
using :expected-result.  See `ert-test-result-type-p' for a
description of valid values for RESULT-TYPE.

Macros in BODY are expanded when the test is defined, not when it
is run.  If a macro (possibly with side effects) is to be tested,
it has to be wrapped in `(eval (quote ...))'.")
         (docstring
          (concat
           (or user-docstring
               (format "Test macro generated by `deftestfixture'.%s"
                       (if fixture-form
                           (format "\nFixture: %S" fixture-form)
                         "")))
           ert-usage))
         (assert-msg
          (format "\"%s\" expects its first argument to be a string literal"
                  name))
         (wrap-expr
          (if fixture-form
              `(list
                (cl-subst (cons 'progn actual-body) '&body
                          ',fixture-form))
            'actual-body)))
    `(progn
       (puthash ',name t deftestfixture--registry)
       (cl-defmacro ,name (description &optional tags &rest body)
         ,docstring
         (declare (indent defun))
         (cl-assert (stringp description) nil ,assert-msg)
         (let*
             ((replacements
               `((" " . ,deftest-space)
                 ("`" . "") ("'" . "")
                 ("," . "︐") ("`" . "‵")
                 (";" . "︔") ("[" . "⁅") ("]" . "⁆")))
              (provided-tags (seq--into-list (and (vectorp tags) tags)))
              (test-name
               (concat
                (if provided-tags
                    (format "%s··⇨··"
                            (s-join "︐" (mapcar #'prin1-to-string
                                                provided-tags)))
                  "")
                (thread-last description s-trim s-collapse-whitespace
                             (s-replace-all replacements))))
              (method-being-tested
               (thread-last description s-trim (s-split " ") car
                            (s-replace-all replacements)))
              (actual-body (if (vectorp tags) body (cons tags body)))
              (wrapped-body ,wrap-expr))
           `(ert-deftest ,(intern test-name) ()
              :tags ',(cons method-being-tested provided-tags)
              ,@wrapped-body))))))

;; The identity fixture: no wrapping, just string-based naming.
(deftestfixture deftest)

;; ═══════════════════════════════════════════════════════════════════
;; define-relation -- relational test fixtures with snapshot updating
;; ═══════════════════════════════════════════════════════════════════

(defun define-relation--show-diff (expected actual)
  "Show a magit-styled diff of EXPECTED vs ACTUAL.
We use `magit-diff-mode' + `magit-diff-wash-diffs' rather than plain
`diff' so we get full magit syntax highlighting, collapsible hunks,
and all the usual magit keybindings."
  (let ((file-a (make-temp-file "snapshot-expected-"))
        (file-b (make-temp-file "snapshot-actual-")))
    (with-temp-file file-a (insert expected))
    (with-temp-file file-b (insert actual))
    (let ((buf (get-buffer-create "*Snapshot Diff*")))
      (with-current-buffer buf
        (let ((inhibit-read-only t))
          (erase-buffer)
          (insert (shell-command-to-string
                   (format "git diff --no-index --color=never -- %s %s"
                           (shell-quote-argument file-a)
                           (shell-quote-argument file-b))))
          (goto-char (point-min))
          (magit-diff-mode)
          (magit-diff-wash-diffs '("--no-index"))))
      (delete-file file-a)
      (delete-file file-b)
      (pop-to-buffer buf))))

(cl-defmacro define-relation (name params docstring &rest body)
  "Define a relational test fixture named NAME with PARAMS.

This is the declarative counterpart to `deftestfixture': where
`deftestfixture' wraps arbitrary test bodies in a fixture,
`define-relation' declares a *relation* among parameters -- some
inputs, some outputs -- and generates a test macro, a compute
function (for snapshot update), and all the `C-u C-x C-e'
plumbing automatically.

NAME is a symbol (e.g., `work-item').  The generated test macro
is `define-NAME-test'; the internal checker is `NAME--check'.

PARAMS is a list of symbols.  Each becomes a keyword argument in
the generated test macro (`:stack', `:results-in', etc.).  The
body receives them as lexical bindings.

DOCSTRING documents the relation.

BODY performs the relational check.  It may call `should' for
assertions and MUST return a plist whose keys (a keyword subset
of PARAMS) are the **output keys** -- the expectations that
`C-u C-x C-e' can auto-fill from the actual computed values.
By way of example, `(list :results-in rendered)' declares
`:results-in' as the output key with `rendered' as the actual
value.

During snapshot update (`C-u C-x C-e'), the body executes with
`ert-fail' suppressed (`cl-letf'), so `should' becomes a no-op
and the body runs to completion -- returning the output plist
even when the assertion would fail.

Example:

  (define-relation widget (input expected-output)
    \"Verify INPUT transforms to EXPECTED-OUTPUT.\"
    (let ((actual (transform input)))
      (should (equal expected-output actual))
      (list :expected-output actual)))

  ;; Generates `define-widget-test':
  (define-widget-test \"round-trip preserves data\" [widget]
    :input \"hello\"
    :expected-output \"HELLO\")

  ;; C-u C-x C-e rewrites :expected-output from actual."
  (declare (indent 3))
  (let* ((check-fn    (intern (format "%s--check" name)))
         (compute-fn  (intern (format "%s--compute" name)))
         (update-at   (intern (format "%s--update-at" name)))
         (update-fn   (intern (format "%s--update" name)))
         (update-by   (intern (format "%s--update-by-name" name)))
         (test-macro  (intern (format "define-%s-test" name)))
         (param-keywords (mapcar (lambda (p) (intern (format ":%s" p))) params))
         (assert-msg  (format "\"%s\" expects its first argument to be a string literal"
                              test-macro)))
    `(progn
       ;; -- 1. The checker: body verbatim, params as arguments --
       (defun ,check-fn ,params ,docstring ,@body)

       ;; -- 2. Compute: call checker with ert-fail suppressed --
       (defun ,compute-fn (plist)
         ,(format "Call `%s' with `should' suppressed; return output plist." check-fn)
         (cl-letf (((symbol-function 'ert-fail) #'ignore)
                   ((symbol-function 'ert--signal-should-execution) #'ignore))
           (,check-fn ,@(cl-loop for kw in param-keywords
                                 collect `(plist-get plist ,kw)))))

       ;; -- 3. Update helpers --
       (defun ,update-at (form-start)
         ,(format "Rewrite output keys of the `%s' form at FORM-START." test-macro)
         (save-excursion
           (goto-char form-start)
           (let* ((form (sexp-at-point))
                  (rest (cddr form))
                  (plist (if (vectorp (car rest)) (cdr rest) rest))
                  (outputs (,compute-fn plist)))
             ;; For each output key, find and replace its value in the buffer.
             (cl-loop for (key val) on outputs by #'cddr do
                      (goto-char form-start)
                      (search-forward (format "%s" key))
                      (forward-sexp)
                      (let ((end (point)))
                        (backward-sexp)
                        (delete-region (point) end)
                        (insert (prin1-to-string val))))
             ;; Re-eval and run.
             (goto-char form-start)
             (forward-sexp)
             (eval-last-sexp nil)
             (message "Snapshot updated."))))

       (defun ,update-fn ()
         ,(format "Rewrite output keys of the `%s' form at point." test-macro)
         (save-excursion
           (backward-sexp)
           (,update-at (point))))

       (defun ,update-by (description)
         ,(format "Find the `%s' with DESCRIPTION in any buffer, update its snapshot." test-macro)
         (let ((needle (format ,(format "(%s %%S" test-macro) description))
               (found nil))
           (cl-loop for buf in (buffer-list)
                    when (buffer-file-name buf) do
                    (with-current-buffer buf
                      (save-excursion
                        (goto-char (point-min))
                        (when (search-forward needle nil t)
                          (backward-char (length needle))
                          (,update-at (point))
                          (setq found t)
                          (cl-return)))))
           (unless found
             (user-error "Could not find %s %S in any open buffer"
                         ',test-macro description))))

       ;; -- 4. Test macro --
       (cl-defmacro ,test-macro (description &optional tags &rest plist-body)
         ,docstring
         (declare (indent defun))
         (cl-assert (stringp description) nil ,assert-msg)
         (let*
             ((replacements
               `((" " . ,deftest-space)
                 ("`" . "") ("'" . "")
                 ("," . "︐") ("`" . "‵")
                 (";" . "︔") ("[" . "⁅") ("]" . "⁆")))
              (provided-tags (seq--into-list (and (vectorp tags) tags)))
              (test-name
               (concat
                (if provided-tags
                    (format "%s··⇨··"
                            (s-join "︐" (mapcar #'prin1-to-string
                                                provided-tags)))
                  "")
                (thread-last description s-trim s-collapse-whitespace
                             (s-replace-all replacements))))
              (method-being-tested
               (thread-last description s-trim (s-split " ") car
                            (s-replace-all replacements)))
              (actual-plist (if (vectorp tags) plist-body (cons tags plist-body)))
              ;; Bind function symbols so the inner backquote can
              ;; reference them with a single comma (,--check-fn)
              ;; instead of double-comma (,,check-fn) which would
              ;; try to evaluate the symbol as a variable.
              (--check-fn ',check-fn)
              (--compute-fn ',compute-fn)
              (--update-by ',update-by)
              ;; Build the argument list for the checker.
              ;; We quote each value so that symbols (:to latex) and
              ;; lists (:using ((org-defblock ...))) survive splicing
              ;; into the ert-deftest expansion.  Quoting strings and
              ;; nil is a no-op, so this is backward-compatible.
              (call-args
               (cl-loop for kw in ',param-keywords
                        collect `',(plist-get actual-plist kw)))
              ;; Collect output keys: call compute at macro-expand time
              ;; to discover which keys are outputs.  We pass the plist
              ;; values as-is (they're literals in snapshot tests).
              (output-keys
               (condition-case nil
                   (cl-loop for (k _) on (,compute-fn actual-plist) by #'cddr
                            collect k)
                 (error nil))))
           `(ert-deftest ,(intern test-name) ()
              :tags ',(cons method-being-tested provided-tags)
              ;; Happy path: check-fn runs should internally.
              ;; On failure: catch it, compute actual outputs, re-assert
              ;; with ert-info buttons for [Show Diff] / [Update Snapshot].
              (condition-case nil
                  (funcall ',--check-fn ,@call-args)
                (ert-test-failed
                 (let ((--outputs (funcall ',--compute-fn
                                           (list ,@(cl-loop
                                                    for kw in ',param-keywords
                                                    append (list kw `',(plist-get actual-plist kw)))))))
                   ,@(cl-loop
                      for kw in output-keys
                      for expected = (plist-get actual-plist kw)
                      collect
                      `(ert-info
                           (`(lambda ()
                               (when (stringp ,expected)
                                 (insert-button "[Show Diff]"
                                                'action (lambda (_)
                                                          (define-relation--show-diff
                                                           ,expected
                                                           (plist-get --outputs ,kw)))
                                                'follow-link t
                                                'help-echo "Show diff of expected vs actual")
                                 (insert "  "))
                               (insert-button "[Update Snapshot]"
                                              'action (lambda (_)
                                                        (funcall ',--update-by ,description))
                                              'follow-link t
                                              'help-echo "Rewrite output keys in source")
                               ""))
                         (should (equal ,expected (plist-get --outputs ,kw)))))))))))

       ;; -- 5. Registry entry with metadata --
       (puthash ',test-macro
                (list :updater #',update-fn
                      :compute #',compute-fn)
                deftestfixture--registry))))

(provide 'snap)
;;; snap.el ends here
